export const GET_MEMES_REQUESTED = 'GET_MEMES_REQUESTED';
export const GET_MEMES_SUCCESS = 'GET_MEMES_SUCCESS';
export const GET_MEMES_FAILED = 'GET_MEMES_FAILED';
export const INC_PAGE = 'INC_PAGE';
export const DEC_PAGE = 'DEC_PAGE';
